-- TIGRAI DATABASE SETUP SCRIPT
-- Generated on: 2025-12-24
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS icerikler;
CREATE TABLE icerikler (
	id INTEGER NOT NULL, 
	baslik VARCHAR NOT NULL, 
	tur VARCHAR NOT NULL, 
	kategoriler VARCHAR, 
	ozet TEXT, 
	yil INTEGER, 
	imdb_puani FLOAT, 
	olusturma_tarihi DATETIME, poster_url TEXT, 
	PRIMARY KEY (id)
);
DROP TABLE IF EXISTS puanlar;
CREATE TABLE puanlar (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	kullanici_id INTEGER NOT NULL, 
	icerik_id INTEGER NOT NULL, 
	puan INTEGER NOT NULL, 
	puanlama_tarihi DATETIME, 
	FOREIGN KEY(kullanici_id) REFERENCES kullanicilar (id), 
	FOREIGN KEY(icerik_id) REFERENCES icerikler (id)
);
DROP TABLE IF EXISTS movies;
CREATE TABLE "movies" (
"adult" TEXT,
  "belongs_to_collection" TEXT,
  "budget" TEXT,
  "genres" TEXT,
  "homepage" TEXT,
  "id" TEXT,
  "imdb_id" TEXT,
  "original_language" TEXT,
  "original_title" TEXT,
  "overview" TEXT,
  "popularity" TEXT,
  "poster_path" TEXT,
  "production_companies" TEXT,
  "production_countries" TEXT,
  "release_date" TEXT,
  "revenue" REAL,
  "runtime" REAL,
  "spoken_languages" TEXT,
  "status" TEXT,
  "tagline" TEXT,
  "title" TEXT,
  "video" INTEGER,
  "vote_average" REAL,
  "vote_count" REAL
);
DROP TABLE IF EXISTS shows;
CREATE TABLE "shows" (
"show_id" TEXT,
  "type" TEXT,
  "title" TEXT,
  "director" TEXT,
  "cast" TEXT,
  "country" TEXT,
  "date_added" TEXT,
  "release_year" INTEGER,
  "rating" TEXT,
  "duration" TEXT,
  "listed_in" TEXT,
  "description" TEXT
);
DROP TABLE IF EXISTS books;
CREATE TABLE "books" (
"bookID" INTEGER,
  "title" TEXT,
  "authors" TEXT,
  "average_rating" REAL,
  "isbn" TEXT,
  "isbn13" INTEGER,
  "language_code" TEXT,
  "  num_pages" INTEGER,
  "ratings_count" INTEGER,
  "text_reviews_count" INTEGER,
  "publication_date" TEXT,
  "publisher" TEXT
);
DROP TABLE IF EXISTS kullanicilar;
CREATE TABLE kullanicilar (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            kullanici_adi TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            olusturma_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        , is_admin INTEGER DEFAULT 0);
DROP TABLE IF EXISTS yorumlar;
CREATE TABLE yorumlar (
	id INTEGER NOT NULL, 
	kullanici_id INTEGER NOT NULL, 
	icerik_id INTEGER NOT NULL, 
	yorum_metni TEXT NOT NULL, 
	olusturma_tarihi DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kullanici_id) REFERENCES kullanicilar (id), 
	FOREIGN KEY(icerik_id) REFERENCES icerikler (id)
);
DROP TABLE IF EXISTS password_reset_tokens;
CREATE TABLE password_reset_tokens (
	id INTEGER NOT NULL, 
	kullanici_id INTEGER NOT NULL, 
	token VARCHAR NOT NULL, 
	expires_at DATETIME NOT NULL, 
	used INTEGER, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kullanici_id) REFERENCES kullanicilar (id)
);
DROP TABLE IF EXISTS chat_history;
CREATE TABLE chat_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            kullanici_id INTEGER NOT NULL,
            message TEXT NOT NULL,
            is_user INTEGER DEFAULT 1,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(kullanici_id) REFERENCES kullanicilar(id)
        );
CREATE INDEX ix_icerikler_baslik ON icerikler (baslik);
CREATE INDEX ix_icerikler_tur ON icerikler (tur);
CREATE INDEX ix_icerikler_id ON icerikler (id);
CREATE INDEX ix_puanlar_id ON puanlar (id);
CREATE INDEX ix_yorumlar_id ON yorumlar (id);
CREATE UNIQUE INDEX ix_password_reset_tokens_token ON password_reset_tokens (token);
CREATE INDEX ix_password_reset_tokens_id ON password_reset_tokens (id);
CREATE INDEX idx_chat_history_kullanici_id ON chat_history (kullanici_id);
-- SEED DATA: Users
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (1, 'test_user', 'test_user@temp.com', '7bfef5f3381db8b6b814bfcb0d781aa9$afdaea91310e8bb7a45d784add1c9f0205f2f6465bf8fb0f4f60f04a83b0dbe2', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (2, 'demo_user', 'demo_user@temp.com', '7bfef5f3381db8b6b814bfcb0d781aa9$afdaea91310e8bb7a45d784add1c9f0205f2f6465bf8fb0f4f60f04a83b0dbe2', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (3, 'aleyna', 'aleyna@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (4, 'test_user_cli_2', 'test_user_cli_2@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (5, 'a', 'a@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (6, 'abc
', 'abc@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (7, 'aa', 'aa@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (8, 'aaa', 'aaa@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (9, 'AAAA', 'AAAA@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (10, 'aaaa', 'aaaa@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (11, 'derA', 'derA@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (12, 'aaleyana', 'aaleyana@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (13, 'dera', 'dera@temp.com', '5f2a798a5b65af67e6966155b79f1ff7$f5c8c26c1d10a243762bcfbe925c7ddd9c1ee21e1078315b8e35ab302214bcb6', '2025-12-16 15:59:17', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (14, 'admin', 'admin@example.com', '7bfef5f3381db8b6b814bfcb0d781aa9$afdaea91310e8bb7a45d784add1c9f0205f2f6465bf8fb0f4f60f04a83b0dbe2', '2025-12-17 09:17:22.202463', 1);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (16, 'Aleyna', 'aleynaa@temp.com', 'ef11cc8eab606bddef9cb151c367649c$ed516ba3d7fc501fb1f9e1d5f11bae8a2325db4447518f4c154290689f904210', '2025-12-20 17:13:19.659675', 1);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (17, 'MemoryTester', 'test_memory@tigrai.com', 'dummy', '2025-12-22 11:05:40.144242', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (18, 'guvenlik_demo', 'guvenlik_demo@example.com', 'a292a47f8b6f6e7034b911e570b06b2b$2caa4c87d2232d3071ef2d76e2e937d1175c3b6b89a544a0a69f7c4be55175e8', '2025-12-22 11:13:58', 0);
INSERT INTO kullanicilar (id, kullanici_adi, email, password_hash, olusturma_tarihi, is_admin) VALUES (19, 'vajvavajVajzvah', 'fshsvB@temp.com', 'fe0f04c93a8306ddba6e8315543385a5$0ac9069b9fe9c0cb095b51d6b17fc48764e3f983ae8913976444daecc25b793a', '2025-12-23 09:20:46.561809', 0);
-- SEED DATA: Content (Films, Books, Series)
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (1525, 'The Haunted World of Edward D. Wood, Jr.', 'Film', 'Documentary', 'The strange life and the wonderfully awful films of 1950''s Hollywood Z movie director Ed Wood are profiled in this documentary that was conceived of and researched several years before commercial-filmmaker Tim Burton made his feature film tribute. Actually, Wood does not appear much in this film. Rather, it centers on the lives and thoughts of his entourage and those who knew him. Among those interviewed are Wood''s former lover and star of his earliest films, Dolores Fuller, whom he abruptly replaced in the middle of Bride of the Monster with actress Loretta King who is also interviewed.', 1996, 10.0, '2025-12-12 16:15:22.117375', 'https://image.tmdb.org/t/p/w500/rarwGANB2L4EcxInVw1Q8TgcfU1.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (3450, 'Stiff Upper Lips', 'Film', 'Comedy', 'Stiff Upper Lips is a broad parody of British period films, especially the lavish Merchant-Ivory productions of the ''eighties and early ''nineties. Although it specifically targets A Room with a View, Chariots of Fire, Maurice, A Passage to India, and many other films, in a more general way Stiff Upper Lips satirises popular perceptions of certain Edwardian traits: propriety, sexual repression, xenophobia, and class snobbery.', 1998, 10.0, '2025-12-12 16:15:23.049117', 'https://image.tmdb.org/t/p/w500/qozMEPtSjU3bvKS9E4DNYzW1h8u.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (4514, 'The Tic Code', 'Film', '', 'A 10 year old gifted boy wants to be a jazz pianist much to the chagrin of his more classical oriented piano instructor. With his mother''s help, he is an underage regular at a local nightspot, where he is teamed up with a sax superstar. Both come to learn that each suffers from Tourette''s Syndrome (thus the film title). The older man has developed mannerisms to cover up his own fallibilities and resents the boy and his mother''s acceptance of the disease.', 2000, 10.0, '2025-12-12 16:15:23.681958', 'https://image.tmdb.org/t/p/w500/8R03pVm4ECjvITfZ7JKyvFIM49r.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (14833, 'Dinosaurs!  A Fun-Filled Trip Back In Time', 'Film', '', 'The video—with beginning scenes filmed in 1987—begins with a young boy named Phillip (played by Fred Savage) sitting in his bedroom, listening to loud music, and struggling to find an idea for a class report on a science topic. While struggling to find some ideas-and annoying his mother (offscreen) with his loud music- a song plays on his boom box, titled Mesozoic Mind, and the song provides him with an inspiration for his report: DINOSAURS!  Philip then goes to sleep and has a dream where he discovers that the search for the truth about these magnificent animals and their astonishing 160-million-year success on earth is probably the most fascinating speculation there is. Phillip then finishes his report and presents it to the class. The class report is then covered through the 1980 claymation short Dinosaur by Will Vinton Productions.', 1987, 10.0, '2025-12-12 16:15:58.036397', 'https://image.tmdb.org/t/p/w500/yrho3PbjV6MqxsCpLSWrwwut4q6.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (15717, 'The Flight That Fought Back', 'Film', 'Documentary, Drama', 'A docudrama about the efforts of the passengers aboard United Airlines Flight 93 to derail the 9/11 terrorists plan for the hijacked airliner.', 2004, 10.0, '2025-12-12 16:16:02.816857', 'https://image.tmdb.org/t/p/w500/xHVmgQjBIPWWW34Tpjc6tRF8Mbo.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (16853, 'My Foolish Heart', 'Film', '', 'After a long absence, Mary Jane visits her schoolfriend Eloise, and Eloise''s daughter Ramona. Eloise drinks too much and is unhappily married to Lew Wengler. Eloise falls asleep and remembers her time with her true love, Walt Dreiser, at the beginning of the Second World War. She recalls the events that lead up to her split with Mary Jane, and how Lew married Eloise rather than Mary Jane.', 1950, 10.0, '2025-12-12 16:16:09.589666', 'https://image.tmdb.org/t/p/w500/hTeRZeDAX3UUgGnfzBqGUwWyAI6.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (18700, 'Canned Dreams', 'Film', 'Documentary', 'A simple can of ravioli propels this spectacular 30,000-kilometre, eight-country journey through all phases of food production and the far flung sources of international ingredients. A dream-like voyage with glimpses of disconcerting realities, the story begins with a single mother toiling in one of the biggest open pit mines in Brazil and ends on the shelf of a grocery store in Finland. Along the way, the workers whose calloused hands mine, raise and harvest each ingredient reveal their dreams and hopes, like the Danish pig farmer who loves his sows but longs for a girlfriend, and the Portuguese tomato picker who wants to stay healthy long enough to pay her daughters way through university. Sumptuous photography and impressive sound design make an eloquent statement about our modern, globalized world, making us aware of the hundreds of invisible people who prepare the food we eat every day. -Gisèle Gordon (HotDocs.ca)', 2012, 10.0, '2025-12-12 16:16:20.841744', 'https://image.tmdb.org/t/p/w500/cwyBaaRT71QSn04OQpMhDGZUrr4.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (19145, 'The Union', 'Film', 'Music, Documentary', 'In November 2009, filmmaker Cameron Crowe began filming a behind-the-scenes look at the creation of the album The Union, a collaboration between musicians Elton John and Leon Russell, who hadn''t spoken to one another in 38 years prior to beginning work on the album. In addition, the documentary offers a rare glimpse into the process John goes through to create and compose his music. Featured in the film are musicians Neil Young, Brian Wilson, Booker T. Jones, steel guitarist Robert Randolph, Don Was and a 10-piece gospel choir who all contribute to the album, which is produced by award-winning producer T-Bone Burnett. Musician Stevie Nicks and John''s long-time lyricist Bernie Taupin also appear.', 2012, 10.0, '2025-12-12 16:16:23.781403', 'https://m.media-amazon.com/images/M/MV5BMjI0ODAwMTc0OV5BMl5BanBnXkFtZTcwNzg5NDk4Nw@@._V1_SX300.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (20701, 'The Late, Great Planet Earth', 'Film', 'Documentary', 'The Late, Great Planet Earth is the title of a best-selling 1970 book co-authored by Hal Lindsey and Carole C. Carlson, and first published by Zondervan. The book was adapted in 1979 into a movie. The Late, Great Planet Earth is a treatment of literalist, premillennial, dispensational eschatology. As such, it compared end-time prophecies in the Bible with then-current events in an attempt to broadly predict future scenarios leading to the rapture of believers before the tribulation and Second Coming of Christ to establish his thousand-year (i.e. millennial) Kingdom on Earth.', 1979, 10.0, '2025-12-12 16:16:34.397638', 'https://image.tmdb.org/t/p/w500/xqHt4IQcH3caAiKbcImyCldu6gk.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (21829, 'The White Shadow', 'Film', '', 'The White Shadow is a British drama film directed by Graham Cutts based on the novel "Children of Chance" by Michael Morton. Alfred Hitchcock worked on it as assistant director and also handled the writing, editing, and art direction.  The film was long thought to be lost. In August 2011, it was announced that the first three reels of the six-reel picture had been found in a garden shed and donated to the NFPF. The film cans were mislabled Two Sisters and Unidentified American Film and only later identified. The film was restored by Park Road Studios and is now in the New Zealand Film Archive.', 1924, 10.0, '2025-12-12 16:16:43.120338', 'https://image.tmdb.org/t/p/w500/gtfnuORiotKI18g0YBeG34rugdZ.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (22102, 'هیچ کجا هیچ کس', 'Film', 'Mystery, Crime, Drama', '', 2013, 10.0, '2025-12-12 16:16:45.308230', 'https://image.tmdb.org/t/p/w500/8BzFyXeHSDU9f5RE1EbdjYJx0L5.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (22129, 'The Guide', 'Film', 'Comedy', 'Nine frustrated young architects in an equally frustrated city. A comedy about sexuality, Athens and modern Greeks.  Iasonas arrives in Athens starting his new ambitious career as “architects’ guide”. His group consists of international students of architecture, finishing their Erasmus in Thessaloniki. Soon Iasonas faces the contradicting wishes of the students who prefer a day-long coffee or a visit to a graveyard than a guide to the Acropolis. Meanwhile, he meets back with his once (more than just a) best friend Mirsini. Trapped between a friend who progressively sees him less and less as a friend and a group that sees him less and less as a guide, Iasonas will have to give an answer to all his personal questions regarding his sexuality and his career.', 2011, 10.0, '2025-12-12 16:16:45.545488', 'https://image.tmdb.org/t/p/w500/duQnk1HgS5ynbYhReKnvAH0vj3A.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (22148, 'Meat the Truth', 'Film', 'Documentary', 'Meat the Truth is a high-profile documentary which forms an addendum to earlier films on climate change. Although such films have succeeded in drawing public attention to the issue of global warming, they have repeatedly ignored one of the most important causes of climate change: the intensive livestock production. Meat the Truth draws attention to this by demonstrating that livestock farming generates more greenhouse gas emissions worldwide than all cars, lorries, trains, boats and planes added together.', 2008, 10.0, '2025-12-12 16:16:45.692343', 'https://image.tmdb.org/t/p/w500/ANTsGDien6MwXKndxObZQIoz3c.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (22313, 'Eggshells', 'Film', 'Fantasy, Drama', 'Experimental allegorical story about a group of hippie students in Austin, Texas, who move into an old big house in the woods. However, something else is there and it''s influencing them.', 1969, 10.0, '2025-12-12 16:16:47.019100', 'https://image.tmdb.org/t/p/w500/qlaGO8llKWfnmQhwDmNg6kczJ6J.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (23344, 'Bloodline', 'Film', 'Horror', 'Sandra''s twin sister was brutally murdered by a serial killer when they were children. Fifteen years later Sandra is now a professional journalist whose career is on the fritz. Sandra is given one last shot - an assignment which will prove the toughest of her life. She is sent back to the location of her sister''s murder to shoot a behind-the-scenes expose for a hardcore porn flick. There she will be forced to confront the ghosts of her past as a new copycat killer has his sights set on Sandra.', 2011, 10.0, '2025-12-12 16:16:55.670543', 'https://image.tmdb.org/t/p/w500/AnA1Jiuxjkm5GtqsanReFKhZX3T.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (23452, 'Slaying the Badger', 'Film', 'Documentary', 'Before Lance Armstrong, there was Greg LeMond, who is now the first and only American to win the Tour de France. In this engrossing documentary, LeMond looks back at the pivotal 1986 Tour, and his increasingly vicious rivalry with friend, teammate, and mentor Bernard Hinault. The reigning Tour champion and brutal competitor known as “The Badger,” Hinault ‘promised’ to help LeMond to his first victory, in return for LeMond supporting him in the previous year. But in a sport that purports to reward teamwork, it’s really every man for himself.', 2014, 10.0, '2025-12-12 16:16:56.596123', 'https://image.tmdb.org/t/p/w500/qkQ1h7W1h0V9ydcXXQ5ob1kGiR2.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (23895, 'The Bride from Hades', 'Film', 'Horror', 'On the night of the summer Obon festival, Hagiwara Shinzaburo meets a beautiful courtesan named Otsuyu. Not knowing she''s a ghost, he becomes infatuated by her.', 1968, 10.0, '2025-12-12 16:17:00.364073', 'https://image.tmdb.org/t/p/w500/xrejo0tLkgfNrpkHmBW2Tkm9IMR.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (24466, 'Double Tide', 'Film', '', 'Artist and filmmaker Sharon Lockhart is known for creating beautiful, meditative films that incorporate subtle movement and a static, photographic gaze to examine her subjects. Her new film, Double Tide, documents the work of a female clam digger in the mudflats of coastal Maine and is filmed on the rare occasion in which low tide occurs twice within daylight hours—once at dawn and once at dusk.', 2009, 10.0, '2025-12-12 16:17:05.417304', 'https://image.tmdb.org/t/p/w500/3WYMMQCv2Z2T3FjaZAcETplEzZ8.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (24814, 'The Great Kidnapping', 'Film', 'Crime', 'In early seventies Italy, plagued by criminality and political terrorism, a fearless police commissioner is sent to restore law and order in a northern industrial town devastated by a recent wave of violence and kidnappings..', 1973, 10.0, '2025-12-12 16:17:08.420709', 'https://image.tmdb.org/t/p/w500/mpJM5IjG47QCv3kGuQ8Mqfk0Jmb.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (25182, 'Symphony of the Soil', 'Film', 'Documentary, Adventure', 'Drawing from ancient knowledge and cutting edge science, Symphony of the Soil is an artistic exploration of the miraculous substance soil. By understanding the elaborate relationships and mutuality between soil, water, the atmosphere, plants and animals, we come to appreciate the complex and dynamic nature of this precious resource. The film also examines our human relationship with soil, the use and misuse of soil in agriculture, deforestation and development, and the latest scientific research on soil’s key role in ameliorating the most challenging environmental issues of our time. Filmed on four continents, featuring esteemed scientists and working farmers and ranchers, Symphony of the Soil is an intriguing presentation that highlights possibilities of healthy soil creating healthy plants creating healthy humans living on a healthy planet.', 2013, 10.0, '2025-12-12 16:17:11.586749', 'https://image.tmdb.org/t/p/w500/2ECOJwW7BvlH5w4sQf3nni4MqGv.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (26419, 'Willow and Wind', 'Film', 'Drama', 'A boy breaks a window at his school and sets out to fix it on his own during a storm.', 2000, 10.0, '2025-12-12 16:17:23.211041', 'https://image.tmdb.org/t/p/w500/mpO6dIP6hAGkniOMyH9NZ3Dz33O.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (26825, 'Vessel of Wrath', 'Film', 'Comedy, Drama, Romance', 'Ginger Ted, AKA Edward Claude Wilson (Charles Laughton) a drunkard and womanizer, and Miss Jones,(Elsa Lanchester) a missionary, live in the Alas Islands. During a cholera epidemic, Ginger Ted and Miss Jones are sent to an outlying part of the islands to run a hospital; on their return, their motorboat breaks down, and they are marooned overnight on a small island.', 1938, 10.0, '2025-12-12 16:17:27.506605', 'https://image.tmdb.org/t/p/w500/eEL8WAXMTkSr9p8TKeyTLtIb7ob.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (27781, 'The incredible Paris Incident', 'Film', 'Action, Adventure, Comedy, Science Fiction', 'Argoman has a silly costume and is a sexist pig. He uses his special telekinetic to get the ladies to sleep with him. The catch is, after a night with a gal he loses his special powers for 6 hours!  In this comedic super/spy thriller, Argoman goes head to head against the evil Jenabelle: Queen of the World.', 1967, 10.0, '2025-12-12 16:17:37.222603', 'https://image.tmdb.org/t/p/w500/rSEO8lJQytxur3FOId4XMfiVhE3.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (27870, 'Absolute Aggression', 'Film', 'Action, Science Fiction, Thriller', 'In the year 2011, the prison system is run by the private sector. Business tycoon R.D. Crowley (Robert Davi) has created a Virtual Reality prison. The prisoner''s bodies are locked in suspended animation while their mind traverses the lethal labyrinth of games Crowley has designed for them. Crowley allows wealthy sportsmen to participate, for a price, in deadly VR combat with the prisoners.', 2004, 10.0, '2025-12-12 16:17:38.188343', 'https://image.tmdb.org/t/p/w500/uFoDacIvDooPzoO8uKeMir9JOrk.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (28369, 'One Night Only', 'Film', 'Comedy', 'A group of female friends get together with some hired "ladies of the evening", and make some quick cash for throwing a raunchy party for the local hockey team.', 1986, 10.0, '2025-12-12 16:17:43.287545', 'https://image.tmdb.org/t/p/w500/oYAduyoeg3UWSzAvnGqagelLHTP.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (28385, 'Crooks and Coronets', 'Film', 'Comedy', 'Two crooks are hired to rob an eccentric old lady''s estate, but once they get to know her, they can''t bring themselves to do it.', 1969, 10.0, '2025-12-12 16:17:43.439336', 'https://image.tmdb.org/t/p/w500/wrLYTSVCwi2dYzyY95aFK8ZZnKV.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (28687, 'Garrison Keillor: The Man on the Radio in the Red Shoes', 'Film', '', 'Americas foremost humorist and commentator, Garrison Keillor, takes his skits and jokes, music and monologues across the country in his traveling radio show, spinning his stories into American gold. This free form, intimate look at the private man in the public spotlight goes behind the scenes of Americas most popular radio show, A Prairie Home Companion, and inside the imagination of the man who created it.', 2009, 10.0, '2025-12-12 16:17:46.618073', 'https://image.tmdb.org/t/p/w500/y65AKAO3vBlvKMZOm7aQ8XB4EiM.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (29154, 'At Ellen’s Age', 'Film', 'Drama', 'A German flight attendant''s life spirals downward after she leaves her husband, quits her job, and joins a radical group of animal rights activists.', 2010, 10.0, '2025-12-12 16:17:51.630881', 'https://image.tmdb.org/t/p/w500/oGF9hN2xYA4hHv6IxbXp03aYNW5.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (29194, 'Zodiac: The Race Begins...', 'Film', 'Animation, Adventure', 'Ringo the Rat (voice of Tom Arnold) and his pal Oriole the Ox compete in a big race, and discover that persistence and teamwork are just as important as speed when it comes to crossing the finish line first. Determined to thwart the plans of her long time enemy, the Jade Emperor, she sets forth to prevent the success of the Race be impeding the 12 chosen ones.', 2006, 10.0, '2025-12-12 16:17:52.010171', 'https://image.tmdb.org/t/p/w500/jAxhFxtz5Yf9PJfrPHzpVcDxcav.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (29288, 'Backyard Dogs', 'Film', 'Action, Comedy', 'Two teenage boys aspire to win a backyard wrestling championship and a chance to appear on a national TV show.', 2001, 10.0, '2025-12-12 16:17:53.099406', 'https://image.tmdb.org/t/p/w500/ayrCNUHTsk817uAvaK0bnqCyNO.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (29308, 'The Prospects', 'Film', '', 'In Brooklyn live two young street musicians who since childhood dream of building a recording studio together. Charlie, who plays the banjo, just inherited a house with a large basement. His best friend and manager Ted thinks it might be the perfect place for the studio but they need $ 25,000 to fulfill their dream. One day a Jamaican nurse approaches them on the street asking for help to lift a patient who has fallen down. Ted finds a collection of rare baseball cards in the house of the patient, and soon will plot a plan to steal the valuable collection to finance their studio. But when Charlie gets involved in a relationship with the nurse, Ted plans will be disrupted and his friendship with Charlie threatened.', 2011, 10.0, '2025-12-12 16:17:53.312950', 'https://image.tmdb.org/t/p/w500/jeEMgPjbZenscGSMLrdxrcGaQdu.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (29480, 'Intangible Asset Number 82', 'Film', 'Documentary', 'The search for an enigmatic South Korean shaman, and the inspiration found on the journey, renews a jazz musician''s faith in the power of music.', 2008, 10.0, '2025-12-12 16:17:55.089581', 'https://image.tmdb.org/t/p/w500/hYLHG5dBR3jr15wH9mDtj1xeYAs.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (30190, 'The Mother Of Invention', 'Film', 'Comedy', 'A mockumentary about an aspiring inventor who dreams of winning an annual young inventor award. The only problem is... he''s never made an invention that works.', 2010, 10.0, '2025-12-12 16:18:02.634519', 'https://image.tmdb.org/t/p/w500/rLBA5XEI7qlJey5ClAVOs9qKDk6.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (31672, 'Andrew Jenks, Room 335', 'Film', '', 'To get to know the world he lives in, college kid Andrew Jenks doesn''t take off to remote, exotic places with a backpack, but instead decides to go and stay in a retirement home in Florida for a few weeks. There, he gets acquainted with Tammy, Libby, Dotty and Bill, all of whom are past their prime. These few weeks turn into a valuable experience for Jenks, who approaches the elderly people with an open mind and takes a close look at the less cheerful sides of old age, including decay and dependence.', 2008, 10.0, '2025-12-12 16:18:16.763161', 'https://image.tmdb.org/t/p/w500/itlsSDdnkAHa2ZIY8SQIWLve6IK.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (32138, 'Comoediae 1: Acharenses/Equites/Nubes/Vespae/Pax/Aves', 'Kitap', 'Aristophanes/F.W. Hall/W.M. Geldart', 'Author: Aristophanes/F.W. Hall/W.M. Geldart', 1922, 10.0, '2025-12-12 16:18:17.639755', 'https://covers.openlibrary.org/b/isbn/0198145047-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (32298, 'Willem de Kooning: Late Paintings', 'Kitap', 'Julie Sylvester/David Sylvester', 'Author: Julie Sylvester/David Sylvester', 2006, 10.0, '2025-12-12 16:18:17.709461', 'https://covers.openlibrary.org/b/isbn/382960226X-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (32365, 'Literature Circle Guide: Bridge to Terabithia: Everything You Need For Successful Literature Circles That Get Kids Thinking  Talking  Writing—and Loving Literature', 'Kitap', 'Tara MacCarthy', 'Author: Tara MacCarthy', 2002, 10.0, '2025-12-12 16:18:17.763682', 'https://covers.openlibrary.org/b/isbn/0439271711-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (32739, 'Middlesex Borough (Images of America: New Jersey)', 'Kitap', 'Middlesex Borough Heritage Committee', 'Author: Middlesex Borough Heritage Committee', 2003, 10.0, '2025-12-12 16:18:18.015767', 'https://covers.openlibrary.org/b/isbn/0738511676-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (34692, 'A Key to the Bedroom', 'Film', 'Comedy, Romance', 'In the beginning of a new century the capital of Russia is just amazing and full of poets, beautiful women and arts...', 2003, 10.0, '2025-12-12 16:18:18.823178', 'https://image.tmdb.org/t/p/w500/ktpZMYWEF6smDGOvGYo6auf3YwZ.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (34706, 'OMG, I''m a Robot!', 'Film', 'Comedy, Science Fiction', 'A sensitive guy finds out he''s... a robot.', 2015, 10.0, '2025-12-12 16:18:19.039805', 'https://image.tmdb.org/t/p/w500/gnFpmSOAHr5oqWlJj0idDhQBgtx.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (35627, 'Zone of the Enders: The 2nd Runner Official Strategy Guide', 'Kitap', 'Tim Bogenn', 'Author: Tim Bogenn', 2003, 10.0, '2025-12-12 16:18:20.013977', 'https://covers.openlibrary.org/b/isbn/0744002354-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (36261, 'The Diamond Color Meditation: Color Pathway to the Soul', 'Kitap', 'John  Diamond', 'Author: John  Diamond', 2006, 10.0, '2025-12-12 16:18:20.579264', 'https://covers.openlibrary.org/b/isbn/1890995525-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (36396, 'Bulgakov''s the Master and Margarita: The Text as a Cipher', 'Kitap', 'Elena N. Mahlow', 'Author: Elena N. Mahlow', 1975, 10.0, '2025-12-12 16:18:20.699900', 'https://covers.openlibrary.org/b/isbn/0533017424-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (36480, 'The Complete Theory Fun Factory: Music Theory Puzzles and Games for the Early Grades', 'Kitap', 'Ian        Martin/Katie Elliott', 'Author: Ian        Martin/Katie Elliott', 2004, 10.0, '2025-12-12 16:18:20.809274', 'https://covers.openlibrary.org/b/isbn/0851621813-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (36997, 'The Goon Show  Volume 4: My Knees Have Fallen Off!', 'Kitap', 'NOT A BOOK', 'Author: NOT A BOOK', 1996, 10.0, '2025-12-12 16:18:21.262482', 'https://covers.openlibrary.org/b/isbn/0563388692-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (36999, 'The Goon Show  Volume 11: He''s Fallen in the Water!', 'Kitap', 'NOT A BOOK', 'Author: NOT A BOOK', 1995, 10.0, '2025-12-12 16:18:21.263707', 'https://covers.openlibrary.org/b/isbn/0563388323-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (37166, 'Winchester Shotguns', 'Kitap', 'Dennis Adler/R.L. Wilson', 'Author: Dennis Adler/R.L. Wilson', 2008, 10.0, '2025-12-12 16:18:21.438122', 'https://covers.openlibrary.org/b/isbn/0785821082-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (37167, 'Colossians and Philemon: A Critical and Exegetical Commentary (International Critical Commentary)', 'Kitap', 'R. McL. Wilson', 'Author: R. McL. Wilson', 2005, 10.0, '2025-12-12 16:18:21.438759', 'https://covers.openlibrary.org/b/isbn/0567044718-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (37689, 'Taxation of Mineral Rents', 'Kitap', 'Ross Garnaut', 'Author: Ross Garnaut', 1983, 10.0, '2025-12-12 16:18:21.916857', 'https://covers.openlibrary.org/b/isbn/0198284543-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (37747, 'The New Big Book of America', 'Kitap', 'Todd Davis/Marc Frey', 'Author: Todd Davis/Marc Frey', 2002, 10.0, '2025-12-12 16:18:21.977336', 'https://covers.openlibrary.org/b/isbn/0762412631-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (37992, 'Field Guide to Home Buying in America', 'Kitap', 'Mark LeVine/Michael Pollan/Stephen M. Pollan', 'Author: Mark LeVine/Michael Pollan/Stephen M. Pollan', 1988, 10.0, '2025-12-12 16:18:22.234267', 'https://covers.openlibrary.org/b/isbn/0671639617-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (38256, 'Delwau Duon: Peintiadau Nicholas Evans = Symphonies in Black: The Paintings of Nicholas Evans', 'Kitap', 'Nicholas    Evans/Rhonda  Evans', 'Author: Nicholas    Evans/Rhonda  Evans', 1987, 10.0, '2025-12-12 16:18:22.511346', 'https://covers.openlibrary.org/b/isbn/0862431352-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (38443, 'Pourquoi Israël', 'Film', 'Documentary', 'Using interviews and other footage shot especially for this documentary, French director Claude Lanzmann investigates the state of Israel in 1972. This movie concentrates on Israelis going about their business of everyday living.', 1973, 10.0, '2025-12-12 16:18:21.465505', 'https://image.tmdb.org/t/p/w500/t9RKoSA1hQDV6StT8Wb7NUxNBja.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (40146, 'Fanning the Flame: Bible  Cross  and Mission', 'Kitap', 'Chris    Green/Chris Wright/Paul Douglas Gardner', 'Author: Chris    Green/Chris Wright/Paul Douglas Gardner', 2003, 10.0, '2025-12-12 16:18:24.701907', 'https://covers.openlibrary.org/b/isbn/0310249872-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (40846, 'Oliver Wendell Holmes in Paris: Medicine  Theology  and the Autocrat of the Breakfast Table', 'Kitap', 'William C. Dowling', 'Author: William C. Dowling', 2007, 10.0, '2025-12-12 16:18:25.669254', 'https://covers.openlibrary.org/b/isbn/1584655801-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (40888, 'Tyrannosaurus Wrecks (Stanley  #1)', 'Kitap', 'Laura Driscoll/Alisa Klayman-Grodsky/Eric     Weiner', 'Author: Laura Driscoll/Alisa Klayman-Grodsky/Eric     Weiner', 2003, 10.0, '2025-12-12 16:18:25.706797', 'https://covers.openlibrary.org/b/isbn/0786845031-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (41357, 'The Irish Anatomist: A Study of Flann O''Brien', 'Kitap', 'Keith Donohue', 'Author: Keith Donohue', 2003, 10.0, '2025-12-12 16:18:26.233854', 'https://covers.openlibrary.org/b/isbn/1930901356-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (41483, 'The American Campaign: U.S. Presidential Campaigns and the National Vote', 'Kitap', 'James E. Campbell', 'Author: James E. Campbell', 2000, 10.0, '2025-12-12 16:18:26.451924', 'https://covers.openlibrary.org/b/isbn/089096940X-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (41528, 'His Princess Devotional: A Royal Encounter With Your King', 'Kitap', 'Sheri Rose Shepherd', 'Author: Sheri Rose Shepherd', 2007, 10.0, '2025-12-12 16:18:26.587812', 'https://covers.openlibrary.org/b/isbn/1590529626-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (41884, 'Bill Gates: Computer Legend (Famous Lives)', 'Kitap', 'Sara Barton-Wood', 'Author: Sara Barton-Wood', 2001, 10.0, '2025-12-12 16:18:27.094403', 'https://covers.openlibrary.org/b/isbn/0739844326-L.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (42543, 'Dream Deceivers: The Story Behind James Vance vs. Judas Priest', 'Film', '', 'A chilling post mortem on the tragic case of two teenagers who decided to shoot themselves in the head with a shotgun, and the ensuing court case staged to place the blame on the heavy metal band Judas Priest.', 1992, 10.0, '2025-12-12 16:18:26.606712', 'https://image.tmdb.org/t/p/w500/lssGutsue6PaWY1mHRVjq8e3B81.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46026, 'Great Transport', 'Film', 'War', 'This WW2 epic was one of the last movies of that kind made in former Yugoslavia. It tells the true story of great transport of Partizans from Vojvodina to Bosnia in 1943.', 1983, 10.0, '2025-12-12 16:18:36.855412', 'https://image.tmdb.org/t/p/w500/3en60tqKsRxhudOsuRAMZDnJrit.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46139, 'Poor, Poor Pavel', 'Film', 'Drama, Foreign', 'Lenfilm''s most recent major production spins a kind of historical fantasy based on real incidents that''s full of ominous implications for today. One night, a patrol rushes into the chambers of the Russian prince Pavel, son of the Empress Catherine; the Empress has died, and Pavel is to be anointed the new Tsar. Thought to be feeble-minded at best and crazy at worst, Pavel soon lives up to his enemies'' fears: he dismisses long-serving courtiers, demands that peasants only work three days a week, and declares that state officials should start their days at 5 am. Soon, it seems that everyone who can is trying to hatch some kind of plot against him - including his own sons. Sumptuously designed, POOR POOR PAVEL constrasts the imperial splendor of the court with the sordid atmosphere of conspiracies and backstabbing that comes to define these characters'' lives.', 2003, 10.0, '2025-12-12 16:18:38.149186', 'https://image.tmdb.org/t/p/w500/1GyidIR1zmmWLn0ASUsOgZmfM06.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46145, 'Sentimentalnyy roman', 'Film', '', 'Near the close of the Russian Civil War, in 1923, a young man begins studying journalism at a worker newspaper and has a series of romantic adventures which cause him to mature swiftly. He rescues a beautiful girl from an abusive family situation, only to lose her to a smooth-talking sharpster the first time he has to leave town on assignment. Another much nicer and more principled girl is really in love with him, but he doesn''t know it. This bittersweet coming-of-age story was based on a novel by Vera Panova.', NULL, 10.0, '2025-12-12 16:18:38.214357', 'https://placehold.co/300x450/9b59b6/ffffff/png?text=Sentimentalnyy%20roman');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46238, 'Brave Revolutionary', 'Film', '', 'Lack-lustred and alcoholic Pratap Narayan Tilak is given a rude awakening when he meets with journalist Megha Dixit, and decides to instill some sense of justice and fair play within his community, and get them to assertively defend their rights and freedom. He is met with strong resistance, both from within his very own community, the police, and some very powerful and influential politicians. Unable to bear the injustice, and frustrated at his community to act proactively, Pratap decides to take the law into his own hands, resulting in chaos, violence, and uncertainty for everyone, and a path to his own grave.', 1994, 10.0, '2025-12-12 16:18:39.312295', 'https://image.tmdb.org/t/p/w500/zAb2YxgYSJTcloGTHAA9ogOVq7M.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46556, 'The Secret of Queen Anna or Musketeers 30 Years Later', 'Film', 'Adventure', 'The 3rd part of the famous trilogy by Alexandre Dumas about d''Artagnan and his 3 friends Athos, Porthos and Aramis.', 1993, 10.0, '2025-12-12 16:18:43.096502', 'https://image.tmdb.org/t/p/w500/l7tgXN4iRWFNYAhgFXhBG8ERawr.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46564, '713-й просит посадку', 'Film', 'Action, Drama', '', 1961, 10.0, '2025-12-12 16:18:43.178436', 'https://image.tmdb.org/t/p/w500/6vkoPXy5d36GQhJ8CJ8LYbxy3og.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46803, 'The House Across the Street', 'Film', 'Horror, Thriller', 'Amy has moved east from Kansas, determined to start a new life. She thinks she has found the perfect small quiet town, a great neighborhood on a quiet street. As she moves into her brand new apartment, eager to start a dream job, happy to befriend her neighbors, she finds out that not everything is as it seems, especially at the house across the street.', 2015, 10.0, '2025-12-12 16:18:45.904210', 'https://image.tmdb.org/t/p/w500/pzTtfN1srzSqWZFvPneV68la5lO.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (46813, 'Souls of Zen: Ancestors and Agency in Contemporary Japanese Temple Buddhism', 'Film', 'Documentary', 'The Japanese population’s reaction to the catastrophe of March 2011 has been described as “stoic” by the Western media. The Japanese code of conduct is indeed deeply rooted in their Buddhist traditions, and young filmmakers Tim Graf and Jakob Montrasio observe in detail what this means for the people and their religion. At graveyards, in temples, at monasteries and with families, they question the impact this triple affliction has had on the lives and beliefs of the inhabitants. How deeply do their beliefs affect their grieving? What role do the monks play in assisting people with their grief? And, what effects has this enormous catastrophe had on their religious rituals? SOULS OF ZEN inserts the events of March 2011 into the context of traditional Zen Buddhism, examining Japan’s religiousness and the beliefs of those practising it at a crucial turning point.', 2012, 10.0, '2025-12-12 16:18:46.012723', 'https://image.tmdb.org/t/p/w500/rS8N0od43nCXmXJfUEV8MuFs3NL.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (47363, 'Cheer Cheer Cheer!', 'Film', 'Comedy', 'Momoko (Yui Aragaki) is a quiet and lonely high school girl who''s only passion is to cheer traditional cheer squad, but all she could gather were good for nothing guys, who could not find places in school. They start the cheer squad with a disaster, but when they finally find the true meaning of "cheering" someone, their passion becomes power and gives strength to those that are cheered.', 2008, 10.0, '2025-12-12 16:18:52.388086', 'https://image.tmdb.org/t/p/w500/uORlSC0O38d8hUc8pMdt0v9vQrk.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (47814, 'Looking for Grace', 'Film', 'Drama', 'When rebellious 16-year-old Grace takes off, her exasperated mum and dad enlist the help of a close-to-retirement detective, and begin the long drive from Perth out to the West Australian wheatbelt to try to find her. On the journey, the two must confront the realities of their changing relationship to one another, and to their daughter…', 2016, 10.0, '2025-12-12 16:18:57.782264', 'https://image.tmdb.org/t/p/w500/dDTE3PgHmWu6XPsTTlnDLsYOVKs.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (48331, 'Acéphale', 'Film', '', 'In common with other Zanzibar films, Patrick Deval’s Acéphale (1968) eschews conventional narrative in favour of an experimental arrangement of austerely executed but intensely hallucinatory episodes that build into a nightmarish fever of isolation and hopelessness.', 1969, 10.0, '2025-12-12 16:19:04.284490', 'https://image.tmdb.org/t/p/w500/gaU8bANlV3JgWIlpqRQmc0HxY2s.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (48784, 'Shuttlecock Boys', 'Film', 'Drama', 'Shuttlecock Boys revolves around the lives, successes and failures of four friends who hail from lower-middle-class backgrounds in Delhi. Should we accept what life offers to us on a platter or should we try to chase our dreams, taking the path less taken? That’s the question our protagonists Gaurav, Manav, Pankaj and Loveleen seek answer to, as they decide to embark upon an eventful journey that will change the course of their lives and careers forever. The one thing that unites these four friends is their common love for badminton. Every evening they meet for a couple of games in their neighborhood joking about their lives and pulling each other’s legs. This part of the day is the most pleasant part of their otherwise dreary lives. While playing badminton one such night, they decide to do something on their own. This very attempt becomes their lifeline putting them on a litmus test of determination, courage, luck and spirit of friendship.', 2012, 10.0, '2025-12-12 16:19:09.937595', 'https://image.tmdb.org/t/p/w500/dMHdKTqlhesbooLvjZqhEW8Igt0.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (48980, 'Images of a Relief', 'Film', 'War, Drama', 'Set in Copenhagen during World War II, the film follows a German officer who visits his Danish mistress in the days after the occupation of Denmark has ended.', 1982, 10.0, '2025-12-12 16:19:12.458737', 'https://image.tmdb.org/t/p/w500/goBlGXlywd7h45QHlqMJnoJ9x5I.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (49032, 'A Story of the Forest: Mavka', 'Film', 'Drama, Fantasy, Romance', 'Mavka, a water nymph, loves Lukash, a country youth. Their brief happiness ends when Lukash is forced to marry the shrewish Kilina. The Spirit of the Forest turns Lukash into a wolf as punishment for his infidelity. The strength of Mavka''s love breaks the spell, but Kilina curses the nymph, transforming her into a weeping willow. This beautiful and tragic story is based on a play written in 1912 by Lesya Ukrainka, a Ukrainian poet, writer and political, civil and female activist, and includes mythological characters taken from Ukrainian folklore.', 1980, 10.0, '2025-12-12 16:19:13.118428', 'https://image.tmdb.org/t/p/w500/yXV8SXQXC657jsaWB7DZKwO1u5F.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (49087, 'Godheten', 'Film', 'Documentary', '', 2013, 10.0, '2025-12-12 16:19:13.827147', 'https://image.tmdb.org/t/p/w500/pQ8w65ee1Bc6lJDHvlIqYaAvKrq.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (49203, 'God is on Air', 'Film', 'Comedy, Drama', 'Two Spanish pan-handlers soon find themselves in over their heads when they stumble upon an opportunity to redeem themselves and perhaps the entire planet. The world appears to suffer from rampant poverty, violence and spiritual desperation and the relentless news media force-feeds these images to the Spanish people. A popular reality television show lets the audience decide between life or death for suspected felons, and one of the opportunistic pan-handlers attempts to escape poverty through this raucous and sensational TV program.', 2002, 10.0, '2025-12-12 16:19:15.294946', 'https://image.tmdb.org/t/p/w500/fbT2FJE8hNuz6rc2c3fQwGIw15W.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (49223, 'Kenny Chesney: Summer In 3D', 'Film', '', 'Kenny Chesney summer tour concert', 2010, 10.0, '2025-12-12 16:19:15.532854', 'https://image.tmdb.org/t/p/w500/7GCsndH3whUeHTTi0pMaCxkqWFS.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (49288, 'Love at 16', 'Film', 'Drama, Comedy', '', 2004, 10.0, '2025-12-12 16:19:16.356461', 'https://image.tmdb.org/t/p/w500/7mC74RTIDunweK56dVqD6ZqMEoe.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (50507, 'Ladies'' Doctor', 'Film', 'Comedy', 'Dr. Lo Bianco, debt load, flees abroad and the headquarters avviatissimo study gynecological colleague Giovannaldi. These are adept at gaining the trust of high society and, thanks to the relationship established with the wife of a wealthy manufacturer (enough to get her pregnant), she becomes finance, own the cuckolded husband, a luxury clinic. And there will be a prize for Lobianco.', 1977, 10.0, '2025-12-12 16:19:31.973349', 'https://image.tmdb.org/t/p/w500/oECIfdYgw6fEa02xrp3zRYh4xOG.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (50622, 'Dead Run', 'Film', '', 'The story concerns a boy called Shuji, growing up in a rural area of Japan where the community is divided into "Shore" and "Offshore" - the latter so-named because it is built on reclaimed land. He meets a few main characters, besides his family, that shape his development - gangster Oni-ken (Susumu Terajima) and his hostess girlfriend, an ominous-looking Catholic priest and his congregation-of-one, the troubled and rebellious teenage girl Eri - who also becomes Shuji''s classmate and the object of his adolescent affections. Life in the Shore/Offshore community is not a bundle of joy - the impression is of a community and lifestyle in decay, with the only hope of rejuvenation being a gangster-funded hotel development project that doesn''t exactly inspire the locals either. It''s an environment that does not fill its young inhabitants with much hope or inspiration.', 2005, 10.0, '2025-12-12 16:19:33.524657', 'https://image.tmdb.org/t/p/w500/kn6V4bXBfmz1EDi6dvtTG9jDBLg.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51121, 'The Dragon Lives Again', 'Film', 'Fantasy, Action', 'Everyone''s favorite martial artist ""Bruce"" winds up fighting for his life and soul in hell against an evil Warlord intent on making him mincemeat - and he has recruited some of the 1970s most iconic B-movie characters to help dispatch the great one. But when that won''t do the trick, he uses monsters, mummies and beautiful women to get the little dragon at any cost.', 1977, 10.0, '2025-12-12 16:19:40.222577', 'https://image.tmdb.org/t/p/w500/lPurIwsLJxYxSxlqGpECeA6FtAB.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51142, 'American Hostage', 'Film', 'Thriller, Crime, Drama', 'American Hostage pulls back the curtains on a terrorist plot centered on a group of terrorists holding two American soldiers hostage on U.S. soil. They demand the release of all prisoners of Guantanamo Bay or they will kill the soldiers.', 2016, 10.0, '2025-12-12 16:19:40.517819', 'https://image.tmdb.org/t/p/w500/r5wkDzVPqoho8Iy4XOvYeFGI31P.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51187, 'Sunnyside Up', 'Film', 'Comedy, Music', 'Molly and Bee, sweet young ''working girls,'' live in a cheap room over a New York grocery store. Molly''s idol, wealthy Jack Cromwell, lives in a Long Island mansion but is markedly less happy, since his fiancée Jane won''t discourage her other admirers. Fleeing in his car, Jack ends up in an urban block party where he meets you-know-who.', 1929, 10.0, '2025-12-12 16:19:41.198605', 'https://image.tmdb.org/t/p/w500/ypfjEPNjxJhhgRbCA1STQCCPcR6.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51266, 'Bazodee', 'Film', 'Romance, Drama, Music', 'Set in beautiful Trinidad and Tobago, BAZODEE is a Bollywood style Caribbean musical about being true to yourself and honest in love at all costs.', 2016, 10.0, '2025-12-12 16:19:42.291562', 'https://image.tmdb.org/t/p/w500/e4BsUZ7gPbDIDybmXUr5HvI9LFr.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51276, 'King: A Filmed Record... Montgomery to Memphis', 'Film', 'Documentary', 'A 1970 American documentary film biography of Dr. Martin Luther King, Jr., presented in the form of newsreel footage and segments of recordings by Dr. King, framed by celebrity narrators, including Marlon Brando, Paul Newman, Joanne Woodward, Ruby Dee, James Earl Jones, Clarence Williams III, Burt Lancaster, Ben Gazzara, Charlton Heston, Harry Belafonte, The movie was produced by Richard Kaplan and Ely Landau.', 1970, 10.0, '2025-12-12 16:19:42.442134', 'https://image.tmdb.org/t/p/w500/jeld2y4CsLIvFhiRVom7Thuw7eo.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51763, 'Mamaboy', 'Film', 'Comedy, Drama, Family, Fantasy, Romance, Science Fiction', 'A high school student must hide the fact that he has become pregnant from his family, friends and the school faculty!', 2017, 10.0, '2025-12-12 16:19:49.160157', 'https://image.tmdb.org/t/p/w500/ocsSTZEAbNuz68yqsfbOFlas9N4.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51802, 'People of a Feather', 'Film', 'Documentary', 'The Inuit of Belcher Islands struggle to adapt as their environment changes.', 2012, 10.0, '2025-12-12 16:19:49.698132', 'https://image.tmdb.org/t/p/w500/pn9OfsADQ7xEgalyjeGQPD9Knvo.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (51813, 'Siccin 3: Cürmü Ask', 'Film', 'Horror', 'After a terrible car accident, Sedat will do anything to save a childhood friend – even if it means dealing with demons and ghosts.', 2016, 10.0, '2025-12-12 16:19:49.843963', 'https://image.tmdb.org/t/p/w500/du3PLNB2L8BNshxCOrgfDVyDfV2.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (52101, 'Farewell Baghdad', 'Film', 'Drama', 'Between the years 1950-51 close to 130 thousand Jews left Iraq. The most ancient community in the world ceased to exist.', 2014, 10.0, '2025-12-12 16:19:53.941016', 'https://image.tmdb.org/t/p/w500/lwNLiewOdoGUedZYNc8Ac9mQo7o.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (52112, 'My Night, Your Day', 'Film', 'Crime, Comedy', 'Novák cannot sleep. Not to disturb his girlfriend, he spends his nights in the streets of Budapest and gets into weirder and weirder, more and more impossible and dangerous situations and liaisons. Unless he dies, he may regain his dreams by them.', 2015, 10.0, '2025-12-12 16:19:54.110727', 'https://image.tmdb.org/t/p/w500/jRf2hdMBZyeN703mLaXGOvc1Yla.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (52799, 'The Wild East', 'Film', '', 'The Solar Children, a group of dwarves who left the circus, are trying to start a settlement in the Kyrgyzstan wilderness just after the breakup of the Soviet Union, but are harassed by a gang of bikers. With their meager savings, they hire a ragtag group of heroes to drive off the bikers.', 1993, 10.0, '2025-12-12 16:20:03.824859', 'https://image.tmdb.org/t/p/w500/uUeRz39WxUyhgxFEXEY9PlW8rto.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (52860, 'My Future Love', 'Film', 'Comedy, Drama', 'In 1973, the 20-year-old Svante has a heart condition that the doctors cannot fix. When he has a breakdown on a subway platform, a strange train suddenly appears. He steps into the subway car filled with wonder, without knowing that the destination is the future. In the future he meets Elsa and together they must solve Svante''s problems and figure out how to live together when they are from two different eras.', 2016, 10.0, '2025-12-12 16:20:04.662976', 'https://image.tmdb.org/t/p/w500/chcWPwYgWDnUcoNWXmnlxr5vWzD.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (52953, 'Крепость: щитом и мечом', 'Film', 'War, Animation, Adventure', '', 2015, 10.0, '2025-12-12 16:20:05.901278', 'https://image.tmdb.org/t/p/w500/nwZW2x0uTEwJbOEAy7Gq34QV14q.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53055, 'Bella Vita', 'Film', 'Documentary', 'Bella Vita is an intimate and powerful journey of self-discovery, seeped in culture, tradition, and passion- where family comes first.', 2014, 10.0, '2025-12-12 16:20:07.382638', 'https://image.tmdb.org/t/p/w500/vP44XvOr4If17tme8mRInysCxY2.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53127, 'Panorama of Esplanade by Night', 'Film', '', 'A most perfect picture of the Pan-American Exposition buildings, including the Electric Tower and Temple of Music, as they appear at night.', 1901, 10.0, '2025-12-12 16:20:08.422108', 'https://placehold.co/300x450/f1c40f/ffffff/png?text=Panorama%20of%20Esplanade%20by%20Night');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53363, 'The Black Sheep of Whitehall', 'Film', 'Comedy', 'A professor teaching at a correspondence school  discovers that a Nazi agent is trying to prevent a trade treaty being signed between England and South America.', 1942, 10.0, '2025-12-12 16:20:11.789036', 'https://image.tmdb.org/t/p/w500/dqASaLG6ACSHTFOiHod2LrI6Zzi.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53638, 'Has the Film Already Started?', 'Film', '', '“A pink moving screen will stand at the entrance to the theatre, in the night. One hour before the screening a projectionist will show Griffith’s Intolerance on this screen. The start of the film will be announced at 8.30 but no one will enter before 9.30. During these 60 minutes of waiting, people on the first floor of the building will shake out very dusty carpets, and someone else will throw ice water on the heads of those spectators waiting for the screening. Some actors who have infiltrated the crowd will insult other actors on the first floor. At this moment only, and to stop the beginning of a scandal, the doors of the theatre will open…”', 1951, 10.0, '2025-12-12 16:20:16.179578', 'https://image.tmdb.org/t/p/w500/vzg8m4H2JHiQsCP82vBEjrWnw0r.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53676, 'American Sharia', 'Film', 'Drama, Comedy', 'Fast paced, action packed comedy. Tension flares in The Motor City as Officer Richardson profiles every Muslim he sees as a terrorist. He goes on an arrest frenzy, which makes the community activists, Jihad and Osama take to the streets and rally the people to stand up for their rights. The Chief of Police wants to gain the trust of the Muslim community in order to get re-elected, but Attorney Leila Rodriguez is standing in the way with a discrimination law suit against Officer Richardson and the Motor City Police Department. The Chief calls on his most unreliable detective, Mohammed and partners him with a Middle Eastern, Sharia Law fanatic, Detective Abdul. The Chief wants them to "Speak Muslim To The Muslims" which he thinks will guarantee his re-election.  - Written by Omar Regan', 2015, 10.0, '2025-12-12 16:20:16.742541', 'https://image.tmdb.org/t/p/w500/ad7FHjEN89k9ivwNPSUZebswuZd.jpg');
INSERT INTO icerikler (id, baslik, tur, kategoriler, ozet, yil, imdb_puani, olusturma_tarihi, poster_url) VALUES (53911, 'Christopher Titus: Angry Pursuit of Happiness', 'Film', 'Comedy', 'Known as one of the best and most prolific comedians working today, Christopher Titus releases his sixth 90-minute comedy special, The Angry Pursuit of Happiness, his best performance to date. The show takes the audience on a wild ride from Titus’ solution to the world’s problems,he fixes everything in a way you wont believe, to his insight on “Here’s how life goes” to his ‘me-logy,’ where Titus gives his own eulogy. Titus takes this special to new comedic places he hasn’t gone yet. At an hour and 45 minutes it’s double what a normal special brings, as Titus says “We need comedy to get rid of our desire to kill”', 2014, 10.0, '2025-12-12 16:20:20.455564', 'https://image.tmdb.org/t/p/w500/qqnBOOoVweSp8kedelpWIJKRl5n.jpg');
-- SEED DATA: Ratings
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (51, 1, 999999, 5, '2025-12-23 22:22:05.538853');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (50, 5, 10, 0, '2025-12-23 09:19:23.407861');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (49, 5, 2, 5, '2025-12-23 09:03:42.419927');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (48, 5, 25070, 5, '2025-12-23 09:03:37.762088');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (47, 7, 7, 10, '2025-12-22 12:36:59.588833');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (46, 7, 1050, 3, '2025-12-22 12:36:53.974158');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (45, 7, 1549, 0, '2025-12-22 12:01:21.338773');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (44, 16, 3, 10, '2025-12-22 11:57:38.621238');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (43, 16, 20, 9, '2025-12-22 11:50:49.023875');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (42, 6, 29749, 1, '2025-12-22 11:37:32.359616');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (41, 6, 31447, 0, '2025-12-20 17:22:05.179865');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (40, 5, 42986, 10, '2025-12-20 17:00:35.985097');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (39, 8, 13, 9, '2025-12-17 07:19:28.986141');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (38, 7, 44766, 9, '2025-12-17 07:14:14.749679');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (37, 6, 1008, 10, '2025-12-16 22:40:27.066442');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (36, 6, 6, 10, '2025-12-16 22:36:31.121489');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (35, 6, 15, 2, '2025-12-16 22:31:38.027191');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (34, 6, 1247, 10, '2025-12-16 22:31:31.686555');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (33, 6, 7, 0, '2025-12-16 22:27:56.402118');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (32, 6, 20, 10, '2025-12-16 22:27:48.935808');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (31, 6, 31786, 3, '2025-12-16 22:14:24.834583');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (30, 6, 1213, 4, '2025-12-16 22:14:05.397685');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (29, 6, 13, 0, '2025-12-16 22:13:52.114954');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (28, 7, 18, 5, '2025-12-16 20:59:19.844710');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (27, 7, 21, 10, '2025-12-16 20:59:14.944037');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (26, 7, 741, 2, '2025-12-16 20:58:55.878727');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (25, 1, 763, 9, '2025-12-16 16:18:17.815308');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (24, 13, 31428, 9, '2025-12-16 15:11:48.905211');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (23, 12, 31897, 8, '2025-12-12 14:15:39.682051');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (22, 11, 20, 9, '2025-12-12 13:57:44.888166');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (21, 3, 18, 2, '2025-12-11 18:12:00.630028');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (20, 9, 5, 1, '2025-12-11 13:20:05.599299');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (19, 9, 6, 4, '2025-12-11 13:18:45.648742');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (18, 8, 18, 3, '2025-12-11 12:54:15.180046');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (17, 8, 20, 3, '2025-12-11 12:53:20.385826');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (16, 8, 15, 5, '2025-12-11 12:27:57.500606');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (15, 8, 21, 8, '2025-12-11 12:26:38.407989');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (14, 8, 2, 7, '2025-12-11 12:26:27.582227');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (13, 8, 6, 8, '2025-12-11 12:26:01.942634');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (12, 7, 20, 5, '2025-12-11 09:36:52.186969');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (11, 7, 5, 5, '2025-12-05 11:48:17.848247');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (10, 7, 15, 8, '2025-12-05 11:47:16.106734');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (9, 7, 1, 9, '2025-12-05 11:47:00.556076');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (8, 6, 1, 2, '2025-12-01 13:11:00.972559');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (7, 5, 11, 1, '2025-11-29 10:32:39.947071');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (6, 5, 7, 8, '2025-11-29 10:31:41.883024');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (5, 5, 6, 1, '2025-11-29 10:30:44.007897');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (4, 5, 1, 8, '2025-11-29 10:30:18.941925');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (3, 3, 6, 1, '2025-11-25 10:08:16.743061');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (2, 3, 7, 10, '2025-11-25 10:06:26.367074');
INSERT INTO puanlar (id, kullanici_id, icerik_id, puan, puanlama_tarihi) VALUES (1, 3, 12, 6, '2025-11-25 10:06:17.825038');
COMMIT;
PRAGMA foreign_keys = ON;